server:
  port: ${PORT:8830}
  
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://db-flight/flight}
    username: ${DB_USER:marcello.assis}
    password: ${DB_PASSWORD:cryptic.writings}
    
feign:
  httpclient:
    connection-timeout: 1800000

ribbon:
  ReadTimeout: 1800000
  ConnectTimeout: 1800000
  
rabbitmq:
    host: ${RMQ_HOST:rabbitmq}
    port: ${RMQ_PORT:5672}
    username: ${RMQ_USER:marcello.assis}
    password: ${RMQ_PASSWORD:cryptic.writings}
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${REGISTRY_URL:http://eureka-discovery:8761}/eureka/
  instance:
    preferIpAddress: ${REGISTRY_PREFER_IP:false}
