server:
  port: ${PORT:8810}
  
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5430/passenger}
    username: ${DB_USER:marcello.assis}
    password: ${DB_PASSWORD:cryptic.writings}
  
rabbitmq:
    host: ${RMQ_HOST:localhost}
    port: ${RMQ_PORT:5672}
    username: ${RMQ_USER:marcello.assis}
    password: ${RMQ_PASSWORD:cryptic.writings}
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${REGISTRY_URL:http://localhost:8761}/eureka/
  instance:
    preferIpAddress: ${REGISTRY_PREFER_IP:false}
