server:
  port: ${PORT:9000}

spring:
  application:
    name: gateway-service

zuul:
  prefix: "/api"
  host:
    socket-timeout-millis: 360000
  routes:
    ignoredServices: "*"

feign:
  httpclient:
    connection-timeout: 360000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false 

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    preferIpAddress: ${REGISTRY_PREFER_IP:false}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${REGISTRY_URL:http://HOSTNAME:8761}/eureka/
